config/routes.rb
Rails.application.routes.draw do
  resources :forums do
    resources :comments
  end
  get 'public/index'

  get 'public/profile'

  get 'public/messages_inbox'

  get 'public/requests_inbox'

  get 'public/send_request'

  get 'index/:data' => 'public#index'

  match 'forums/:user_id/new' => 'forums#new', :via => :post


  resources :schools
  resources :tags
  resources :comments
  resources :posts do
    resources :requests
  end
  resources :requests
  resources :messages
  resources :users



  root 'public#login'

  match ':controller(/:action(/:id))', :via=>[:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
	
	# validations

	validates :body, :presence=>true
	validates :to_id, :presence=>true
	
	belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.user_id = session[:user_id]
    @message.read = false
    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :to_id, :read)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(message) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :value=>params[:body] %>
  </div>

  <div class="field">
    <% f.label :to_id %>
    <%= f.text_field :to_id, :value=>params[:to_id], :class=>'opacity_none' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit 'Create Message', :class=>'btn'  %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= User.find(message.to_id).username %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<br>

<%= link_to 'Back', {:controller=>'public',:action=>'index'}, :class=>'btn' %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card-panel">

	<h5>To: <%= link_to(User.find(@message.to_id).username, :controller=>'public', :action=>'profile', :id=>@message.to_id) %><h5>
	<br>
	<%= @message.body %>
	<br>

</div>

<%= link_to 'Messages', {:controller=>'public', :action=>'messages_inbox'}, :class=>'btn' %> 
&nbsp;
<%= link_to 'Back', public_index_path, :class=>'btn' %>