config/routes.rb
Rails.application.routes.draw do
  resources :forums do
    resources :comments
  end
  get 'public/index'

  get 'public/profile'

  get 'public/messages_inbox'

  get 'public/requests_inbox'

  get 'public/send_request'

  get 'index/:data' => 'public#index'

  match 'forums/:user_id/new' => 'forums#new', :via => :post


  resources :schools
  resources :tags
  resources :comments
  resources :posts do
    resources :requests
  end
  resources :requests
  resources :messages
  resources :users



  root 'public#login'

  match ':controller(/:action(/:id))', :via=>[:get, :post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
	
	# validations

	validates :product_name, :presence=>true
	validates :store_name, :presence=>true
	validates :description, :presence=>true
	validates :est_price, :presence=>true
	validates :delivery_location, :presence=>true
	

	belongs_to :user

	belongs_to :forum
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
    
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    
    # try to pass parameters 
    @request.user_id = session[:user_id]
    @request.read = false
    to = Forum.find(@request.forum_id).user.id   
    @request.to_id = to

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:product_name, :store_name, :description, :est_price, :delivery_location, :to_id, :forum_id, :read)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for(request) do |f| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </div>

  <div class="field">
    <%= f.label :store_name %>
    <%= f.text_field :store_name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :est_price, 'Est. Price ($)' %>
    <%= f.text_field :est_price %>
  </div>

  <div class="field">
    <%= f.label :delivery_location %>
    <%= f.text_field :delivery_location, :value=>User.find(session[:user_id]).residence %>
  </div>

  <div class="field">
    <% f.label :forum_id %>
    <%= f.text_field :forum_id, :value=>params[:id], :class=>'opacity_none' %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Request', :class=>'btn' %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requests</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Store name</th>
      <th>Description</th>
      <th>Est price</th>
      <th>Delivery location</th>
      <th>To</th>
      <th>From</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.product_name %></td>
        <td><%= request.store_name %></td>
        <td><%= request.description %></td>
        <td><%= request.est_price %></td>
        <td><%= request.delivery_location %></td>
        <% %>
        <td><%= returnUser(request.to_id) %></td>
        <td><%= returnUser(request.user_id) %></td>
        <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>
<br>
<%= link_to 'Back', {:controller=>'public', :action=>'index'}, :class=>'btn'%>

app/views/requests/show.html.erb
<h5 id="notice"><%= notice %></h5>
<br>

<div class="card-panel">
  <p>
    <strong>Product name:</strong>
    <%= @request.product_name %>
  </p>

  <p>
    <strong>Store name:</strong>
    <%= @request.store_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @request.description %>
  </p>

  <p>
    <strong>Est price:</strong>
    <%= @request.est_price %>
  </p>

  <p>
    <strong>Delivery location:</strong>
    <%= @request.delivery_location %>
  </p>

</div>




<%= link_to 'Back', public_index_path, :class=>'btn' %>